### ISSUE TITLE
how can I remove Help from a Package?

### ISSUE THREAD

**Issue by arcturus140** [OdatNurd/hyperhelp#1]
how can I remove Help from a Package? I created one for test, then deleted the help folder but it is still listed in SublimeText under Browse Available Help.

**Comment by OdatNurd** [comment]
Currently the only way to do that is to manually delete the help files/index associated with the package. For that you'd use `Preferences: Browse Packages` from the command palette or the main menu to go to your packages folder.

Inside of the package that you added help for you can remove the `hyperhelp.json` file to remove the index as well as the associated help files.

Once you do that, quitting and restarting Sublime will make the index go away.
