### ISSUE TITLE
Versioned Documentation [FEATURE]

### ISSUE THREAD

**Issue by arcturus140** [OdatNurd/hyperhelp#2]
### Summary

Replace hyperhelp date with hyperhelp version.

### Expected Behaviour

Documentation is currently using the format

```
%hyperhelp title="Help File Title" date="YYYY-MM-DD"
```

and should instead use the following format

```
%hyperhelp title="Help File Title" version="MAJOR[.MINOR][.PATCH]"
```

### Extra information

Why using a date? Which date, generation date of the source or of the documentation? A date is irrelevant. The documentation should be in sync with whichever version the documentation is used for.

What do you think about this?

**Comment by keith-hall** [comment]
If I understand correctly, changing from a date based header to a version tag one, would add additional burden on the developer/documentation writer to update the help for all documentation topics which are still relevant, to ensure the correct/latest version is shown. This seems like a maintenance nightmare to me, though I agree in principle that versions can be more meaningful than dates. (Sometimes it is nice to know how long a feature was unchanged for, or how recently the help docs were updated etc, which isn't so effortless with version numbers imo...)
I guess some automation could come into play to help update version numbers for existing topics, but there would be more of a disconnect imo with how HyperHelp can currently autocomplete the current date for you, but it would have no way of knowing what will be the next version number you will use to tag a release with.

**Comment by arcturus140** [comment]
you are right it makes more sense to add the major version to the description in hyperhelp.json
